apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livekit.fullname" . }}-config
  labels:
    {{- include "livekit.labels" . | nindent 4 }}
data:
  livekit.yaml: |
    port: {{ .Values.config.port }}
    rtc:
      tcp_port: {{ .Values.config.rtc.tcpPort }}
      udp_port: {{ .Values.config.rtc.udpPort }}
      use_external_ip: {{ .Values.config.rtc.useExternalIp }}
    keys:
      {{- toYaml .Values.config.keys | nindent 6 }}
    room:
      auto_create: {{ .Values.config.room.autoCreate }}
      max_participants: {{ .Values.config.room.maxParticipants }}
    logging:
      level: {{ .Values.config.logging.level }}
