apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit.fullname" . }}
  labels:
    {{- include "livekit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.rtc }}
      targetPort: rtc
      protocol: TCP
      name: rtc
    - port: {{ .Values.service.ports.udp }}
      targetPort: udp
      protocol: UDP
      name: udp
    - port: {{ .Values.service.ports.ws }}
      targetPort: http
      protocol: TCP
      name: ws
  selector:
    {{- include "livekit.selectorLabels" . | nindent 4 }}
